<?php

namespace Entity;

/**
 * Class EntityConfig
 * This file is automatically generated only if it not exist. 
 */

class EntityConfig
{
    public static function getPDOLink(): \PDO
    {
        static $pdo = null;
        if (!$pdo) {
            try {
                $pdo = new \PDO(
                    'mysql:host=127.0.0.1;dbname=thentity;charset=utf8mb4',
                    'root',
                    'test',
                    [
                        \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
                        \PDO::ATTR_DEFAULT_FETCH_MODE => \PDO::FETCH_ASSOC
                    ]
                );
            } catch (\PDOException $e) {
                die('Erreur PDO: ' . $e->getMessage());
            }
        }
        return $pdo;
    }
}
