<?php

namespace Thentity;

/**
 * Abstract Class Test2
 * WARNING: This file is automatically generated by Thentity. 
 * Any manual changes will be overwritten. Do NOT edit this file manually!
 * @property int $id
 * @property int $test_1_id
 * @property float $amount
 * @property string $status
 * @property string $meta
 * @property string $updated_at
 */
#[\AllowDynamicProperties]
abstract class Test2 extends \Thentity\ThentityAbstract
{
    protected static $tableKeys = [
            'id' => [
                'data_type' => 'int',
                'type' => 'int',
                'nullable' => false,
                'auto_increment' => true,
                'precision' => 10,
                'primary_key' => true,
            ],
            'test_1_id' => [
                'data_type' => 'int',
                'type' => 'int',
                'nullable' => false,
                'mandatory' => true,
                'precision' => 10,
            ],
            'amount' => [
                'data_type' => 'decimal',
                'type' => 'float',
                'nullable' => false,
                'default' => 0,
                'precision' => 10,
                'scale' => 2,
            ],
            'status' => [
                'data_type' => 'enum',
                'type' => 'enum',
                'values' => ['pending', 'ok', 'failed'],
                'nullable' => false,
                'default' => 'pending',
                'max_length' => 7,
            ],
            'meta' => [
                'data_type' => 'longtext',
                'type' => 'string',
                'max_length' => 4294967295,
            ],
            'updated_at' => [
                'data_type' => 'timestamp',
                'type' => 'string',
            ],
        ];

    public static function getPrimaryKey(): string
    {
        return 'id';
    }

    public static function getTableName(): string
    {
        return 'test_2';
    }

}
