<?php

namespace Thentity;

/**
 * Abstract Class Test1
 * WARNING: This file is automatically generated by Thentity. 
 * Any manual changes will be overwritten. Do NOT edit this file manually!
 * @property int $id
 * @property string $title
 * @property string $description
 * @property string $created_at
 * @property int $active
 */
#[\AllowDynamicProperties]
abstract class Test1 extends \Thentity\ThentityAbstract
{
    protected static $tableKeys = [
            'id' => [
                'data_type' => 'int',
                'type' => 'int',
                'nullable' => false,
                'auto_increment' => true,
                'precision' => 10,
                'primary_key' => true,
            ],
            'title' => [
                'data_type' => 'varchar',
                'type' => 'string',
                'nullable' => false,
                'mandatory' => true,
                'max_length' => 255,
            ],
            'description' => [
                'data_type' => 'text',
                'type' => 'string',
                'max_length' => 65535,
            ],
            'created_at' => [
                'data_type' => 'datetime',
                'type' => 'string',
                'nullable' => false,
                'default' => 'current_timestamp()',
            ],
            'active' => [
                'data_type' => 'tinyint',
                'type' => 'int',
                'nullable' => false,
                'default' => 1,
                'precision' => 3,
            ],
        ];

    public static function getPrimaryKey(): string
    {
        return 'id';
    }

    public static function getTableName(): string
    {
        return 'test_1';
    }

}
