<?php

namespace Thentity;

/**
 * Abstract Class Test3
 * WARNING: This file is automatically generated by Thentity. 
 * Any manual changes will be overwritten. Do NOT edit this file manually!
 * @property int $id
 * @property int $test_2_id
 * @property string $code
 * @property string $label
 * @property int $enabled
 * @property string $created_at
 */
#[\AllowDynamicProperties]
abstract class Test3 extends \Thentity\ThentityAbstract
{
    protected static $tableKeys = [
            'id' => [
                'data_type' => 'int',
                'type' => 'int',
                'nullable' => false,
                'auto_increment' => true,
                'precision' => 10,
                'primary_key' => true,
            ],
            'test_2_id' => [
                'data_type' => 'int',
                'type' => 'int',
                'precision' => 10,
            ],
            'code' => [
                'data_type' => 'varchar',
                'type' => 'string',
                'nullable' => false,
                'mandatory' => true,
                'max_length' => 32,
                'unique' => true,
            ],
            'label' => [
                'data_type' => 'varchar',
                'type' => 'string',
                'nullable' => false,
                'mandatory' => true,
                'max_length' => 255,
            ],
            'enabled' => [
                'data_type' => 'tinyint',
                'type' => 'int',
                'nullable' => false,
                'default' => 1,
                'precision' => 3,
            ],
            'created_at' => [
                'data_type' => 'datetime',
                'type' => 'string',
                'nullable' => false,
                'default' => 'current_timestamp()',
            ],
        ];

    public static function getPrimaryKey(): string
    {
        return 'id';
    }

    public static function getTableName(): string
    {
        return 'test_3';
    }

}
